### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by parzivail** [EnnuiL/LibZoomer#2]
Are there any plans to put this on Maven? It'd be a lot easier to JIJ that way.

**Comment by EnnuiL** [comment]
Unfortunately, Jitpack (with a release's commit hash being included in the release description) is the only solution that I have for having this mod hosted on a Maven repository; I don't have any kind of web server so I can't host there, I attempted to maintain one in the Git repository itself, but it was a terrible solution that wouldn't last for a long time; If there was a good solution, I'd use it, but yeah, for now, I'm stuck with Jitpack

**Comment by kb-1000** [comment]
You don't actually need to host a maven.
You can use Maven Central to host artifacts for free, in an easily accessible manner (almost everyone has it in their build already, and fabric loom adds it automatically), or if you want your own repository, JFrog has a service with free, managed Artifactory instances.

**Comment by EnnuiL** [comment]
Alright, I'll see if I can get this published to Maven Central

**Comment by EnnuiL** [comment]
Alright, so, it took a long while, I fought against ancient software, got a pair of keys and this mod will be available on Maven Central soon!
Also, one question, did Jitpack not work? Because I used it for Ok Zoomer and it worked just fine

**Comment by parzivail** [comment]
Awesome! On the Jitpack note, it's functional but my understanding is that it's hard for Fabric to version correctly because it's based on commit hashes and not semver. @kb-1000 can correct me if I'm wrong.

**Comment by EnnuiL** [comment]
> 
> 
> Awesome! On the Jitpack note, it's functional but my understanding is that it's hard for Fabric to version correctly because it's based on commit hashes and not semver. @kb-1000 can correct me if I'm wrong.

Oh wait, I think I know exactly what you mean; Ever since I began to use a + instead of a - for the Minecraft version part of the version (it conflicted with the alpha/beta part), Jitpack stopped accepting releases since apparently, the + breaks it; I attempted to work around it by providing commit hashes for Jitpack usage in each GitHub release, but yeah, it's definitely not a real solution
Anyway, yeah, enjoy not having to use commit hashes!
